import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Web Tutorials",
  description: "Generated by YoungHeon",
};

export default function RootLayout({
  children, // page.tsx에서 렌더링한 파일들을 보냄
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        </body>
    </html>
  );
}
